name: CI

on:
  workflow_dispatch:
    
jobs:
  lint:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.2.3"
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.2.app
      - name: Lint
        run: swift format lint --strict -r -p MinWallet
  build-and-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.2.3"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: rust
          target: aarch64-apple-ios-sim,aarch64-apple-ios
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_26.2.app
      - name: Build rust
        run: cd rust && ./build.sh
      - name: Build and test
        run: xcodebuild -scheme MinWallet CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO" -disable-concurrent-destination-testing clean build -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 16 Pro Max,OS=18.5"